### PR TITLE
Ignore excluded and removed packages -- Alternate approach to #26 / #31

### PR DESCRIPTION
**Pull request by wyardley**
Alternate approach to #26, #28, and #30 (though #30 looks Ok to me, other than not excluding removed packages as well).

If there's interest, I'm also happy to take a stab at a PR to get this closer to PEP8 compliance.

### CODE REVIEW

**Comment by Grejeru** [comment]
@calestyo do You plan to merge this PR?

**Comment by wyardley** [comment]
@Grejeru It's looking like nothing has been merged for quite some time (there are quite a few PRs solving a similar problem), so I'm guessing it's not currently maintained actively?

**Comment by Grejeru** [comment]
I have downloaded [Advanced Nagios Plugins Collection](https://github.com/harisekhon/nagios-plugins) and started using their check_yum plugin.

**Comment by wyardley** [comment]
@Grejeru Thanks! Seems like that might be the original author of this one anyway?

**Comment by Grejeru** [comment]
@wyardley it looks like, at least I'm happy as lot of nice plugins I've found there :)

**Pull request closed without merging**
